TeamPOINTless/Areas/Admin/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeamPOINTless.Areas.Admin.Models;

namespace TeamPOINTless.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ContentController : Controller
    {

        private readonly TeamPOINTlessDbContext _db = new TeamPOINTlessDbContext();
        // GET: Admin/Content
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Content
        public ActionResult Content()
        {
            ViewBag.SubjectsList = _db.Subjects.Count();
            ViewBag.NumberOfPages = _db.Pages.Count();
            return View("Content", _db.Subjects.ToList()); 
        }
    }
}

TeamPOINTless/Areas/Admin/Controllers/RoleController.cs
using TeamPOINTless.Areas.Admin.Models;
using TeamPOINTless.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;

namespace TeamPOINTless.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        public RoleController()
        {
        }

        public RoleController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: Admin/Role
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                // Initialize ApplicationRole instead of IdentityRole:
                var role = new ApplicationRole(roleViewModel.Name);

                // Save the new Description property:
                role.Description = roleViewModel.Description;

                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };

            // Update the new Description property for the ViewModel:
            roleModel.Description = role.Description;
            return View(roleModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id,Description")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;

                // Update the new Description property:
                role.Description = roleModel.Description;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

TeamPOINTless/Areas/Admin/Controllers/UserController.cs
using TeamPOINTless.Areas.Admin.Models;
using TeamPOINTless.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace TeamPOINTless.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        //   private ApplicationDbContext db = new ApplicationDbContext();

        public UserController()
        {
        }

        public UserController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: /Users/
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = userViewModel.Email,
                    Email = userViewModel.Email,
                    IsApproved = userViewModel.IsApproved,
                    // Add the Address Info:
                    //                    Address = userViewModel.Address,

                };

                // Add the Address Info:
                //                user.Address = userViewModel.Address;

                // Then create:
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                IsApproved = user.IsApproved,
                EmailConfirmed = user.EmailConfirmed,
                // Include the Addresss info:
                //                Address = user.Address,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,IsApproved,Id,EmailConfirmed")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.IsApproved = editUser.IsApproved;
//                user.Address = editUser.Address;
                user.EmailConfirmed = editUser.EmailConfirmed;
                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }

                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

TeamPOINTless/Areas/Admin/Views/Content/Content.cshtml
@*We use subject list and itereate first the subjects to get the pages. We do this to get the subject title that we need to show that a page belongs to a specific subject. The page do have the subject id it belongs to but for usability we need the subject name. Another way should be to use a pages list here in this view and then before in the controller create a viewbag that contains a list of subject names*@
@model IEnumerable<TeamPOINTless.Areas.Admin.Models.Subject>

@{
    ViewBag.Title = "Content";
}

<h1>Indhold område</h1>
<p>Antal emner: @ViewBag.SubjectsList </p>
<p>Antal sider: @ViewBag.NumberOfPages </p>

@if (Model != null)
{
    <input type="text" id="search" placeholder="Type to search for page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAtOrDefault(0).Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAtOrDefault(0).CreatedDateTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAtOrDefault(0).UpdatedDateTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAtOrDefault(0).Position)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAtOrDefault(0).Visible)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAtOrDefault(0).Content)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAt(0).Id)
                            </th>
                            <th>
                                @Html.DisplayName("Tilhører emne med navn")
                            </th>
                            <th>
                                Tilhører
                                @Html.DisplayNameFor(model => model.Pages.ElementAt(0).SubjectId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAt(0).IsFrontPage)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAt(0).EventDateTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pages.ElementAt(0).ShowEventDateTimeOnFrontPage)
                            </th>
                        </tr>
                    </thead>
                    @foreach (var subject in Model)
                    {
                        @Html.Partial("_Pages", subject.Pages, new ViewDataDictionary { { "title", subject.Title }, { "from", "contentContent" } })
                    }
                </table>
            </div>
        </div>
    </div>
}

TeamPOINTless/Areas/Admin/Views/Content/Index.cshtml
@{
    ViewBag.Title = "Amin Menu";
}

<h1>Administrator Menu</h1>

<h4>Velkommen til admin området. </h4>
<br />
@Html.ActionLink("Håndter website indhold", "Content")<br/>
<br/>
<!--linkText, actionName, controllerName, routeValues, htmlAttributes -->
@Html.ActionLink("Håndter brugere", "Index",
    "User", null /*new {id = item.ID}*/, null)
<br/><br />
@Html.ActionLink("Håndter roller", "Index",
    "Role", null /*new {id = item.ID}*/, null)